# Generated by Django 3.2.18 on 2023-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(max_length=20, verbose_name='type')),
            ],
            options={
                'verbose_name': 'book type',
                'verbose_name_plural': 'book type',
            },
        ),
    ]
