# Generated by Django 3.2.18 on 2023-04-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20230409_2255'),
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwishlistrelationship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='book.book', verbose_name='book'),
        ),
    ]
