# Generated by Django 3.2.18 on 2023-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20230409_2255'),
        ('wish_list', '0002_alter_bookwishlistrelationship_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookwishlistrelationship',
            unique_together={('wish_list', 'book')},
        ),
    ]
