# Generated by Django 3.2.18 on 2023-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('book_name', models.CharField(max_length=20, unique=True, verbose_name='book name')),
                ('book_pic', models.ImageField(blank=True, null=True, upload_to='books/image/%Y/%m', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('brief_introduction', models.CharField(max_length=200, verbose_name='brief introduction')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'book',
            },
        ),
    ]
