# Generated by Django 3.2.18 on 2023-04-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_type', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='book',
            name='b_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_type.booktype', verbose_name='type'),
        ),
    ]
