# Generated by Django 3.2.18 on 2023-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20230403_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='book name'),
        ),
    ]
