# Generated by Django 3.2.18 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(blank=True, null=True, upload_to='book/image/%Y/%m', verbose_name='image'),
        ),
    ]
