# Generated by Django 3.2.18 on 2023-04-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_type', '0001_initial'),
        ('book', '0004_alter_book_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_type.booktype', verbose_name='type'),
        ),
    ]
