# Generated by Django 3.2.18 on 2023-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20230409_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autho',
            field=models.CharField(default=' ', max_length=30, verbose_name='author'),
            preserve_default=False,
        ),
    ]
