# Generated by Django 3.2.18 on 2023-04-04 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='published date'),
        ),
    ]
