# Generated by Django 3.2.18 on 2023-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_alter_bookreview_date_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='date_publish',
            field=models.DateTimeField(auto_now=True, verbose_name='published date'),
        ),
    ]
