# Generated by Django 3.2.18 on 2023-04-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_alter_bookreview_date_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ('-date_publish',), 'verbose_name': 'book review', 'verbose_name_plural': 'book review'},
        ),
    ]
