# Generated by Django 3.2.18 on 2023-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0004_alter_bookreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='N_not_useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='N_useful',
            field=models.IntegerField(default=0),
        ),
    ]
