# Generated by Django 3.2.18 on 2023-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='username', max_length=150, unique=True, verbose_name='user name'),
        ),
    ]
