# Generated by Django 3.2.18 on 2023-04-04 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingplan',
            name='book',
        ),
        migrations.AddField(
            model_name='readingplan',
            name='book_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='book name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='pages_per_day',
            field=models.IntegerField(verbose_name='pages per day'),
        ),
    ]
