# Generated by Django 3.2.18 on 2023-04-10 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_plan', '0002_auto_20230405_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingplan',
            old_name='period',
            new_name='period_days',
        ),
        migrations.AddField(
            model_name='readingplan',
            name='clock_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='last_clock_date',
            field=models.DateTimeField(default=datetime.date(2023, 4, 9)),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='book_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='book name'),
        ),
    ]
