# Generated by Django 3.2.18 on 2023-04-04 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencebook',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
