# Generated by Django 3.2.18 on 2023-04-08 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_b_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preference_book', '0003_alter_preferencebook_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preferencebook',
            unique_together={('user', 'book')},
        ),
    ]
